name: UpdateReadme
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 7"
jobs:
  Mectrics_job:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Sergi Micó Ortiz, sergimicoortiz, sergimicoortiz@gmail.com
          token: ${{ secrets.TOKEN }}
